### PR TITLE
Avoid endless loop.

### PR DESCRIPTION
**Pull request by amosbird**

### CODE REVIEW

**Comment by baskerville** [comment]
Thanks, I would be great if you could provide reproduce steps to trigger the infinite loop.

I'd like to cure the source of the problem rather than the late side effects.

**Comment by amosbird** [comment]
@baskerville To reproduce this, two monitors need to be setup. When only one is activated with a floating  node on current desktop, moving the entire monitor's desktops to the other monitor triggers this. It's a bit hard for me to describe, you might be interested in looking at some of my config files. Cheers!

https://github.com/amosbird/serverconfig/blob/master/scripts/monitormove#L1

https://github.com/amosbird/serverconfig/blob/master/.config/bspwm/bspwmrc#L1

https://github.com/amosbird/serverconfig/blob/master/.config/sxhkd/sxhkdrc#L51

**Comment by alexozer** [comment]
It should be noted though that, at least in my experience, it is possible to experience this with only one monitor.

**Comment by alexozer** [comment]
Unfortunately, although it took 1-2 weeks for it to occur, I just experienced a freeze with this patch and a single monitor.

**Comment by baskerville** [comment]
I can't reproduce this.

The best here would be to provide a state that can be loaded with `bspc wm -l` and a series of `bspc` calls to trigger the crash.

**Comment by MyNameIsCosmo** [comment]
It seems that this relates to #852.

Can anyone confirm if this is fixed by https://github.com/baskerville/bspwm/commit/875defe46997b983bbb3102567bdd68866c202bb?

**Pull request closed without merging**
