### PR TITLE
Make mouse button actions configurable

### PR DESCRIPTION
**Pull request by ideasman42**
Previously this was possible via key bindings, since this operation was removed,
its useful to be able to configure which mouse keys do what.

This example swaps LMB/RMB

```
bspc config pointer_action1 resize_corner
bspc config pointer_action3 move
```

### CODE REVIEW

**Comment by baskerville** [comment]
A few missing things:
- It seems you modified `doc/bspwm.1` directly instead of modifying `doc/bspwm.1.asciidoc` and running `make doc`.
- You shall add the new settings to `contrib/{bash,zsh}_completion`.

**Comment by ideasman42** [comment]
Updated branch based on feedback.

**Comment by baskerville** [comment]
Could you squash those commits?

**Comment by ideasman42** [comment]
squashed

**Comment by baskerville** [comment]
Thanks.

**Pull request merged**
