### PR TITLE
Add setting: no_presel_feedback

### PR DESCRIPTION
**Pull request by sjtio**
Adds a setting called `no_presel_feedback` which prevents drawing preselection feedback. Defaults to `false` as most settings do but it may be nicer to name the setting `presel_feedback` and have it default to `true`.

### CODE REVIEW

**Comment by MyNameIsCosmo** [comment]
Is there anything holding this back from being merged?

**Comment by baskerville** [comment]
@sjtio Yes, `presel_feedback` is better.

**Comment by sjtio** [comment]
Done

**Comment by baskerville** [comment]
Please rebase.

**Comment by sjtio** [comment]
Done

**Comment by baskerville** [comment]
Thanks.

**Pull request closed without merging**
