### PR TITLE
Improve zsh completion

### PR DESCRIPTION
**Pull request by Junak**

### CODE REVIEW

**Comment by baskerville** [comment]
Thanks, I've noticed a few problems (I'm using *zsh 5.3.1*):

When I press `bspc {query,rule} <TAB>` or `bspc subscribe -<TAB>`, I get the following error: `_arguments:comparguments:319: invalid argument: +`. Pressing `bspc subscribe <TAB>` doesn't show me the available options (`-f` and `-c`); the same remark holds for `bspc config`. After pressing `bspc node -g lock<TAB>`, the following string is inserted: `ed=`, but the `=(on|off)` part is optional (the possible completions for `lock` are `locked`, `locked=on` and `locked=off`).

**Comment by Junak** [comment]
The '=' sign is automatically removed if user presses space or return after it.

**Comment by baskerville** [comment]
Ok, thanks.

On my test setup, the completion for `bspc desktop ` starts with:
```
0x00800017  ^1    I   -- I
0x00800018  II    ^2  -- II
0x00800019  III   ^3  -- III
0x0080001A  IV    ^4  -- IV
0x0080001C  ^5    V   -- V
0x0080001D  VI    ^6  -- VI
0x0080001E  VII   ^7  -- VII
0x00800020  VIII  ^8  -- VIII
0x00800021  IX    ^9  -- IX
0x00800022  ^10   X   -- X
```

Could you make the *name* / *index* ordering consistent?

The options for `bspc config` are listed as
```
-d  -- Set settings for the selected desktop
-m  -- Set settings for the selected monitor
-n  -- Set settings for the selected node
```

Would it be possible to use the following item ordering: *monitor*, *desktop* and *node* consistently?

It would seem that everything is sorted alphabetically: is that intentional?

**Comment by Junak** [comment]
>Would it be possible to use the following item ordering: monitor, desktop and node consistently?

Yes. By sorting it manually.

> is that intentional?

If by _international_ you mean whether ordering is influenced by locale than probably yes.

**Comment by baskerville** [comment]
Merged.

**Pull request closed without merging**
