### PR TITLE
Added [-S|--size] flag for floating windows

### PR DESCRIPTION
**Pull request by tmathmeyer**
also modified the ascii doc to for documenting the new flag
example syntax would be:
bspc window -S -10x :: make the currently selected window 10 pixels thinner
bspc window --size 20y :: make the currently selected window 20 pixels taller

This might be doable with the already existing commands, but after looking at the man page for a good half an hour, I couldn't figure it out.

### CODE REVIEW

**Comment by baskerville** [comment]
Thanks!
Have you considered using *scanf* to parse the argument?

**Comment by tmathmeyer** [comment]
So I've switched to sscanf, however It now seems to be jumping randomly instead of resizing properly. I've inspected the variables in GDB, and it seems to be fine; the numbers are all the right values. The only thing I can think of is that 
client_win.floating_rectangle.width
is not giving back the correct dimensions? can you shed any light on this?

**Comment by tmathmeyer** [comment]
I've also discovered that it was happening before the sscanf change; so I'm not sure what's going on, as I cant use gdb to step into the xcb library function.

**Comment by baskerville** [comment]
You need to update the client's floating rectangle.

**Comment by baskerville** [comment]
It might worth mentioning that *xdo* can be used to move and resize floating windows.

**Comment by tmathmeyer** [comment]
Thanks! That would have taken me forever to figure out too...
I have never tried xdo, though I see it is another one of your projects. 
What does this mean for the pull request?

**Comment by tmathmeyer** [comment]
well apparently that doesn't work so well :/
I'll attempt to work on it when I get some more time

**Comment by baskerville** [comment]
You need to pass a pointer to `client_t` to your resize function, not a `client_t`.

**Comment by tmathmeyer** [comment]
So I tried that and I'm still getting weird jumps in window size. Am I calling functions out of order? Or am I disobeying the arcane XCB gods?

**Comment by baskerville** [comment]
The problem is probably that the changes made aren't effective until the next *flush*.

So you should just set the floating rectangle directly instead of relying on `update_floating_rectangle`.

**Pull request closed without merging**
