### PR TITLE
Add events for pointer actions

### PR DESCRIPTION
**Pull request by thwischm**

### CODE REVIEW

**Comment by thwischm** [comment]
fixes #536

**Comment by baskerville** [comment]
I'd like to keep a few free event slots (there can't be more than 32 events) so I think I'd rather go with a single event of the form `pointer_action <monitor_id> <desktop_id> <node_id> move|resize_side|resize_corner begin|end`.

**Comment by thwischm** [comment]
That makes way more sense. I didn't know there could only be 32. That would
explain the compiler warnings though... Sorry, I don't actually know C.

Bastien Dejean <notifications@github.com> schrieb am Fr., 23. Sep. 2016,
17:00:

**Comment by thwischm** [comment]
Could be cleaner with a variable but declaring strings in C isn't as easy as I thought. I should probably leave this to people who actually know what they're doing and learn it properly some time.

**Comment by baskerville** [comment]
Thanks.

**Pull request closed without merging**
