### PR TITLE
Replace query, restore and subscribe with JSON

### PR DESCRIPTION
**Pull request by nfnty**
Appending the flag `--json` to `bspc query` prints the response in JSON.

### CODE REVIEW

**Comment by baskerville** [comment]
Thanks, it seems fine.

Could you provide some background on what led you to add this feature?

**Comment by nfnty** [comment]
Both for automation and readability. See my issue over at #188.

This is my current script for automating desktop setup:

https://gist.github.com/nfnty/8012119577a8563bf3d3

The output is currently not pretty printed due to a bug in Jansson(https://github.com/akheron/jansson/issues/227), but that can be fixed by piping the output to `python -m json.tool`

**Comment by rr-** [comment]
+1, much more convenient to parse JSON than to grep things by hand when implementing Python lemonbar.

**Comment by arianon** [comment]
:+1:, This would be amazing to have!

**Comment by nfnty** [comment]
Rebased against master.

What's stopping this PR from merging?

**Comment by baskerville** [comment]
It would be great to have only one output format for the *query* command. But the *restore* command depends on the output of `bspc query -{T,H,S}`...

Can you provide a JSON implementation of `restore.c`?

Please use camel case key names in JSON: e.g. *splitDirection*, not *Split Direction*.

**Comment by nfnty** [comment]
Sorry for the late reply. I'm doing a complete rewrite and will post a new PR soon. You can check out the progress over at [nfnty/bspwm/json_next](https://github.com/nfnty/bspwm/tree/json_next)

**Comment by baskerville** [comment]
Thanks for putting so much effort into this!

Could you keep the original word order in JSON names: e.g. `firstChild` and not `childFirst`?

**Comment by nfnty** [comment]
Sure! Though it's much easier to parse the output manually when they're named `childFirst` instead of `firstChild`. Maybe the variable names should be changed instead.

**Comment by baskerville** [comment]
Why would it be easier? Could you provide an example?

**Comment by nfnty** [comment]
All keys are sorted alphabetically. I always tend to name all my variables with the most descriptive word first. I.e. `padding` is more descriptive than `bottom`, therefore the variable is named `padding_bottom` instead of `bottom_padding`. Makes it much easier to know which variables are related.

Small example from --desktop with no nodes, generated by `json_serialize_desktop_type()`; --tree output is at least ~220 lines and grows by ~60 lines with each new window for 1 monitor and 10 desktops:

My naming scheme:
```
{
    "focused": false,
    "layout": "tiled",
    "name": "8",
    "nameNext": null,
    "namePrev": "6",
    "nodeRoot": null,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "paddingRight": 0,
    "paddingTop": 0,
    "windowBorderWidth": 1,
    "windowFocus": null,
    "windowGap": 8
}
```
Your naming scheme:
```
{
    "borderWidth": 1,
    "bottomPadding": 0,
    "focusWindow": null,
    "focused": false,
    "layout": "tiled",
    "leftPadding": 0,
    "name": "8",
    "nextName": null,
    "prevName": "6",
    "rightPadding": 0,
    "root": null,
    "topPadding": 0,
    "windowGap": 8
}
```

**Comment by rr-** [comment]
Why can't it be

    {
        "focused": false,
        "layout": "tiled",
        "name":
        {
            "current": "8",
            "next": null,
            "prev": "6"
        },
        "nodeRoot": null,
        "padding":
        {
            "bottom": 0,
            "left": 0,
            "right": 0,
            "top": 0
        },
        "window":
        {
            "borderWidth": 1,
            "focus": null,
            "gap": 8
        }
    }

Plus in most languages, as soon as your JSON string gets converted into actual dictionary, the key order is lost. Victims of this: C++'s `std::map`, python's `dict`, C#'s `IDictionary` etc.

**Comment by nfnty** [comment]
It has to match the underlying structs.

**Comment by rr-** [comment]
Why?

**Comment by nfnty** [comment]
Deserialization. Extremely error prone and way too much code otherwise.

**Comment by rr-** [comment]
But... what deserialization? Wasn't this issue about printing in `bspc query -T`?

**Comment by nfnty** [comment]
Not anymore: [nfnty/bspwm/json_next](https://github.com/nfnty/bspwm/tree/json_next)

**Comment by baskerville** [comment]
@nfnty What do you mean by *parsing the output manually*?

**Comment by nfnty** [comment]
Empirically. I.e. not with a script.

**Comment by baskerville** [comment]
Could you use `JSON_PRESERVE_ORDER` instead of `JSON_SORT_KEYS` in the call to `json_dumpf` and use the suggested, natural, naming scheme?

**Comment by nfnty** [comment]
Yes, but not a very good solution; the output is still hard to manually parse (no way to know where any single key will be due to order being almost completely arbitrary) and the ordering will be lost as soon as anything else touches it.

**Comment by baskerville** [comment]
What's the output of your example with `JSON_PRESERVE_ORDER`?

**Comment by nfnty** [comment]
```
{
    "name": "9",
    "layout": "tiled",
    "root": null,
    "focusWindow": null,
    "prevName": null,
    "nextName": "7",
    "topPadding": 0,
    "rightPadding": 0,
    "bottomPadding": 0,
    "leftPadding": 0,
    "windowGap": 8,
    "borderWidth": 1,
    "focused": false
}
```

**Comment by baskerville** [comment]
Well, it seems to match the insertion order.

Also, the way I see it, the JSON output is meant to be used in conjunction with *jshon* (e.g.: `state=$(bspc query -T -w | jshon -e state -u)`).

The actual position of the object keys shouldn't matter except in rare cases (e.g.: making a diff between two outputs).

**Comment by nfnty** [comment]
Indeed. But it would be very nice with a more logical naming scheme.

`jq` or `python -c 'import json,sys; obj=json.load(sys.stdin); print(obj["name"])` are other good alternatives.

**Comment by nfnty** [comment]
Query and restore seems to be working now. Everything is serialized and deserialized properly. Though more tree restore logic needs to be implemented. I'll be implementing JSON for events now as well.

**Comment by rr-** [comment]
Perhaps it would be a better idea to send PRs in small chunks rather than flipping many things upside down at once...

**Comment by nfnty** [comment]
Everything is tightly coupled and will need to be tested as a whole. JSON events could be sent in a separate PR, but I don't really see why.

**Comment by baskerville** [comment]
This is fine but you might want to change the pull request's title.

**Comment by nfnty** [comment]
Done. Replaced the branch with json_next.

**Comment by nfnty** [comment]
I'll squash commits when everything is finished.

**Comment by nfnty** [comment]
`m == NULL` in both `focus_node` and `transfer_node`, hmm...

**Comment by baskerville** [comment]
Thanks.

I think there might be a problem with `put_status`: you're not sending the event name to the subscribers unless there're subscribers to *all*.

The manual is probably unclear, but this is valid: `bspc control --subscribe monitor_geometry window_activate window_state desktop`.

So you always need to include the event name in the JSON events.

**Comment by nfnty** [comment]
I'll fix it.

**Comment by baskerville** [comment]
Can't `put_status` stay variadic?

**Comment by nfnty** [comment]
Why?

**Comment by nfnty** [comment]
Should I just mark monitor as `NULLABLE` in `json_serialize_status_node` or do you know the reason why `monitor == NULL` during `focus_node` and `transfer_node`?

**Comment by baskerville** [comment]
Is this something I can reproduce on the *json* branch?

**Comment by nfnty** [comment]
Yup. Run `bspc control --subscribe all` and focus empty desktops and transfer windows around. Check warning messages.

**Comment by baskerville** [comment]
What might be `NULL` in `focus_node(m, d, n)` is `n`.

**Comment by baskerville** [comment]
And what might be `NULL` in `transfer_node(ms, ds, ns, md, dd, nd)` is `nd`.

**Comment by nfnty** [comment]
Hmm... Didn't think that would be it. Can't seem to reproduce the `transfer_node` bug now. Well, seems to be finished then.

**Comment by nfnty** [comment]
Still have no clue as to why the warning was for key `monitor`.

**Comment by nfnty** [comment]
Figured it out... Of course, `node == NULL` and then `json_serialize_node_type` return `json_null()`.

**Comment by nfnty** [comment]
Can't use `json_object_set_new` on `json_null()`...

**Comment by nfnty** [comment]
Everything seems to be working now!

**Comment by nfnty** [comment]
Rebased to master.

**Comment by nfnty** [comment]
Fixed restore.c to actually restore desktops, and it's not working properly. Will be fixing `restore_tree` tomorrow.

**Comment by EvanPurkhiser** [comment]
What's up with these numbered `(x)` commits? Seems like those should be squashed down?

**Comment by nfnty** [comment]
Squashed all commits.

**Comment by baskerville** [comment]
`query -W -w` should be equivalent to `query -W -w focused`. The same thing goes for `-d` and `-m` with no arguments (cf. the manual).

Also, `query -W` should return window IDs, not nodes.

Regarding subscribers, the first thing I tried is `control --subscribe window_focus`: it burps an incredible amounts of informations, seems to be out of sync with actual events and the output is cropped. I'm only interested in the monitor name, the desktop name and the window ID: if I need more, I can use `query -T`.

Then I tried `control --subscribe desktop_focus`: it doesn't seem to be receiving anything.

**Comment by nfnty** [comment]
Fixed the buffer issue.

`-m` `--monitor`, `-d` `--desktop`, `-w` `--window` are for single structs and output focused without arguments. The window id can then be directly accessed with `bspc query --window | jq -r .client.window` or further constrained with `MONITOR_SEL`, `DESKTOP_SEL`, `WINDOW_SEL` respectively.

put_status should be an atomic operation and should output all the information pertaining to that status. I could potentially introduce an argument that makes it only output json_serialize_*TYPE*_type information. It is much more expensive to require further queries to get all information needed after a status.

You can see how the statuses are serialized here: [L586-L677](https://github.com/nfnty/bspwm/blob/json/json.c#L586-L677)

**Comment by baskerville** [comment]
The *query* command is a [well-thought design](https://github.com/baskerville/bspwm/wiki/Command-Syntax-Rewrite#query-command) by @Stebalien and I don't see the reason why I would want to change its semantic.

**Comment by nfnty** [comment]
Now old behavior works again.

**Comment by baskerville** [comment]
I changed my mind: I'm only interested in `query -T` being JSON.

In addition, `query -T -{m,d,w} [SEL]` should return the JSON representation of the selected monitor, desktop or node.

Everything else should remain unchanged.

**Comment by nfnty** [comment]
Just wow... Could you give me any technological reasoning?

**Comment by nfnty** [comment]
Everything is now fully implemented and working.

**Comment by nfnty** [comment]
Rebased to master.

**Comment by baskerville** [comment]
`query -T` is meant to expose state and events are meant to communicate state changes *without redundancy*.

**Comment by baskerville** [comment]
There was a misunderstanding about how things should work: sorry about that.

The good news, though, is that most of your work has to do with `{query,restore} -T`.

**Comment by nfnty** [comment]
There is no redundancy in the event messages.

Here is a very lean script showing the powerfulness of the JSON implementation:
https://gist.github.com/nfnty/21a2dca0c17d11c08c8f

The script is toggling screensaver state based on when windows change state to or from fullscreen.

**Comment by nfnty** [comment]
I will update all examples and documentation before merge.

**Comment by baskerville** [comment]
Fixed by 5e9c8e0.

**Comment by nfnty** [comment]
Conclusion:
* Reactive management is extremely inefficient.
* bspwm:
    * low performance
    * illogical and unpredictable
    * inflexible
    * horrible on 4K monitors

Very unpleasant contributing to this project. Hopefully I'll never have to interact with you again.

**Comment by Stebalien** [comment]
@nfnty, you're contributing to someone else's *personal* project; they have every right to be picky about what goes into it. If you don't like it, fork it.

**Comment by cjk** [comment]
Hmm.. strange, up until @nfnty's last comment I had the impression this is a productive and constructive thread and it'll vastly improve the usefulness of bspwm.
Was I that wrong?
Making progress is not always easy and may include setbacks, let's not forget that.

At least I appreciate the effort both of you have contributed!

**Pull request closed without merging**
